# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  base_url = "https://boxes.koumbit.net"

  # If you don't have this plugin, the puppet provisioning will most likely
  # fail. You can fix that by manually downloading the puppet module
  # dependencies of this plugin and placing them in tests/modules/
  if Vagrant.has_plugin?("vagrant-librarian-puppet")
    config.librarian_puppet.puppetfile_dir = "tests"
    config.librarian_puppet.destructive = false
  end

  # All boxes should update, then run tests
  config.vm.provision "shell", inline: "apt-get update"
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "tests"
    puppet.manifest_file = "init.pp"
    puppet.module_path = "tests/modules"
  end

  config.vm.define :jessie do |jessie|
    box = "koumbit/jessie64"
    jessie.vm.box = box
    jessie.vm.box_url = "#{base_url}/#{box}"
  end

  config.vm.define :stretch do |stretch|
    box = "koumbit/stretch64"
    stretch.vm.box = box
    stretch.vm.box_url = "#{base_url}/#{box}"
  end

  config.vm.define :buster do |buster|
    box = "koumbit/buster64"
    buster.vm.box = box
    buster.vm.box_url = "#{base_url}/#{box}"
  end
end
